Set speech = CreateObject("SAPI.SpVoice")
text = "ooooooooooooooooooooooooooooooooooooooooohhhhhhhhhhhhhhhhhhhhh yyyyyyyyyyyyyyyyyeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh mmmmmmmmmmmmmmmmmmmmmmmmmmmmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn"
speech.Speak text
